from __future__ import annotations
 
import asyncio
import hashlib
import logging
import re
from pathlib import Path
from typing import Any
 
import aiofiles
from langchain_core.language_models import BaseChatModel
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
 
from agent.core.planner import APITestCase, TestPlan, UITestCase
 
logger = logging.getLogger(__name__)
 
# ── Conftest template (shared pytest fixtures) ────────────────────────────────
 
CONFTEST_TEMPLATE = '''"""
conftest.py  –  AUTO-GENERATED by QA Agent
Do not edit manually; re-run the agent to regenerate.
"""
import pytest
import httpx
from playwright.sync_api import sync_playwright, BrowserContext, Page
 
# ── Configuration ──────────────────────────────────────────────────────────────
 
BASE_URL: str = "{base_url}"
BROWSER_TYPE: str = "{browser}"   # chromium | firefox | webkit
HEADLESS: bool = {headless}
 
 
# ── HTTP fixtures ──────────────────────────────────────────────────────────────
 
@pytest.fixture(scope="session")
def base_url() -> str:
    """Base URL of the application under test."""
    return BASE_URL
 
 
@pytest.fixture(scope="session")
def http_client(base_url: str):
    """
    Session-scoped httpx client with the base URL pre-configured.
 
    Using session scope means one TCP connection pool is reused across all
    API tests – faster and more realistic than creating a client per test.
    """
    with httpx.Client(base_url=base_url, timeout=10.0) as client:
        yield client
 
 
# ── Playwright fixtures ────────────────────────────────────────────────────────
 
@pytest.fixture(scope="session")
def browser_context() -> BrowserContext:
    """
    Session-scoped Playwright browser context.
 
    A single browser process is launched for the whole test session.
    Individual tests get an isolated Page (below) but share the browser
    binary – significantly faster than launching per test.
    """
    with sync_playwright() as pw:
        launcher = getattr(pw, BROWSER_TYPE)
        browser = launcher.launch(headless=HEADLESS)
        context = browser.new_context(base_url=BASE_URL)
        yield context
        context.close()
        browser.close()
 
 
@pytest.fixture
def page(browser_context: BrowserContext) -> Page:
    """
    Function-scoped Playwright page – fresh and isolated for every test.
 
    Each test gets its own browser tab so navigation state, cookies and
    local storage do not leak between tests.
    """
    pg = browser_context.new_page()
    yield pg
    pg.close()
 
 
# ── Data generation fixtures ───────────────────────────────────────────────────
 
@pytest.fixture(scope="session")
def fake():
    """Faker instance for generating realistic test data."""
    from faker import Faker
    return Faker()
'''
 
# ── LLM system prompts ────────────────────────────────────────────────────────
 
API_TEST_SYSTEM = (
    "You are a senior Python QA engineer. "
    "Write a pytest test function for the API endpoint described. "
    "Use the `httpx` library for HTTP calls. "
    "Import `httpx` and use `BASE_URL` from conftest. "
    "Add clear docstrings and assertions. "
    "Return ONLY the Python function code, no markdown fences, no imports header "
    "(imports will be added automatically)."
)
 
UI_TEST_SYSTEM = (
    "You are a senior QA engineer expert in Playwright (Python). "
    "Write a single pytest test function that uses the `page` fixture from conftest. "
    "Use the `fake` fixture (from the faker library) to generate any necessary realistic test data for filling out forms. "
    "The function should navigate to the page, perform the described action, and assert the result. "
    "Return ONLY the Python function code, no markdown fences."
)
 
FILE_HEADER = '''"""
{filename}
AUTO-GENERATED by QA Agent – do not edit manually.
"""
import pytest
import httpx
 
BASE_URL = "{base_url}"
'''
 
UI_FILE_HEADER = '''"""
{filename}
AUTO-GENERATED by QA Agent – do not edit manually.
"""
import pytest
from playwright.sync_api import Page
 
BASE_URL = "{base_url}"
'''
 
 
class TestGenerator:
    """
    Generates pytest test files from a `TestPlan` using an LLM.
    """
 
    def __init__(self, llm: BaseChatModel, settings: dict):
        self.llm = llm
        self.settings = settings
        self.base_url: str = settings["test_generation"]["base_url"]
        self.browser: str = settings["playwright"]["browser"]
        self.headless: bool = settings["playwright"]["headless"]
        self.out_dir = Path(settings["paths"]["tests_generated"])
 
        self._api_chain = (
            ChatPromptTemplate.from_messages(
                [("system", API_TEST_SYSTEM), ("human", "{spec}")]
            )
            | self.llm
            | StrOutputParser()
        )
        self._ui_chain = (
            ChatPromptTemplate.from_messages(
                [("system", UI_TEST_SYSTEM), ("human", "{spec}")]
            )
            | self.llm
            | StrOutputParser()
        )
 
    # ── Private ──────────────────────────────────────────────────────────────
 
    @staticmethod
    def _sanitise_name(text: str) -> str:
        """Convert arbitrary text to a safe Python identifier fragment."""
        return re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")[:40]
 
    async def _write(self, path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        async with aiofiles.open(path, "w", encoding="utf-8") as fh:
            await fh.write(content)
        logger.info("Generated: %s", path)
 
    async def _generate_api_test(self, tc: APITestCase) -> tuple[str, str]:
        """Return (filename, file_content) for one API test case."""
        spec = (
            f"Endpoint: {tc.method} {tc.endpoint}\n"
            f"Description: {tc.description}\n"
            f"Expected HTTP status: {tc.expected_status}\n"
            f"Payload: {tc.payload}"
        )
        func_code: str = await self._api_chain.ainvoke({"spec": spec})
        name = self._sanitise_name(f"{tc.method}_{tc.endpoint}")
        filename = f"test_{name}.py"
        header = FILE_HEADER.format(filename=filename, base_url=self.base_url)
        return filename, f"{header}\n\n{func_code.strip()}\n"
 
    async def _generate_ui_test(self, tc: UITestCase) -> tuple[str, str]:
        """Return (filename, file_content) for one UI test case."""
        spec = (
            f"Page URL: {self.base_url}{tc.page}\n"
            f"Action: {tc.action}\n"
            f"Assertion: {tc.assertion}"
        )
        func_code: str = await self._ui_chain.ainvoke({"spec": spec})
        name = self._sanitise_name(tc.page)
        filename = f"test_{name}.py"
        header = UI_FILE_HEADER.format(filename=filename, base_url=self.base_url)
        return filename, f"{header}\n\n{func_code.strip()}\n"
 
    # ── Public ───────────────────────────────────────────────────────────────
 
    async def generate(self, plan: TestPlan, _codebase_summary: str) -> list[str]:
        """
        Generate all test files from the plan.
        Returns a list of file paths that were written.
        """
        written: list[str] = []
 
        # conftest.py
        conftest_content = CONFTEST_TEMPLATE.format(
            base_url=self.base_url,
            browser=self.browser,
            headless=str(self.headless),
        )
        conftest_path = self.out_dir / "conftest.py"
        await self._write(conftest_path, conftest_content)
        written.append(str(conftest_path))
 
        # Semaphore to avoid triggering 429 RESOURCE_EXHAUSTED (especially on free tiers)
        max_concurrency = self.settings.get("test_generation", {}).get("max_concurrency", 3)
        delay = self.settings.get("test_generation", {}).get("rate_limit_delay_seconds", 0)
        sem = asyncio.Semaphore(max_concurrency)

        async def _generate_api_bounded(tc):
            async with sem:
                result = await self._generate_api_test(tc)
                if delay > 0:
                    await asyncio.sleep(delay)
                return result

        # API tests – run with bounded concurrency
        if self.settings["test_generation"]["generate_api_tests"]:
            api_tasks = [_generate_api_bounded(tc) for tc in plan.api_tests]
            api_results: list[tuple[str, str]] = await asyncio.gather(*api_tasks)
            for filename, content in api_results:
                path = self.out_dir / "api" / filename
                await self._write(path, content)
                written.append(str(path))
 
        async def _generate_ui_bounded(tc):
            async with sem:
                result = await self._generate_ui_test(tc)
                if delay > 0:
                    await asyncio.sleep(delay)
                return result

        # UI tests
        if self.settings["test_generation"]["generate_ui_tests"]:
            ui_tasks = [_generate_ui_bounded(tc) for tc in plan.ui_tests]
            ui_results: list[tuple[str, str]] = await asyncio.gather(*ui_tasks)
            for filename, content in ui_results:
                path = self.out_dir / "ui" / filename
                await self._write(path, content)
                written.append(str(path))
 
        logger.info("Generator: wrote %d files.", len(written))
        return written